Attribute VB_Name = "TEST_Cases"
'==============================================================================
' MODULE: TEST_Cases
'------------------------------------------------------------------------------
' GENERATED by tools/generate_case_tests.py from tests/fixtures and
' tests/expected. Do not edit: change the JSON files and regenerate.
' python tools/check.py fails when this file is out of date.
'
' PURPOSE
'   Run every numerical test case against the engine. Each procedure writes
'   one fixture into the input sheets for one regime, runs the engine and
'   checks the expected outputs through TEST_CaseRunner.
'
' USAGE
'   Run TEST_Cases.RunCaseTests from the Immediate window in a development
'   workbook. See TEST_CaseRunner for what it changes and restores.
'
' COMPATIBILITY
'   Numbers are passed as text with a "." decimal point and converted with
'   Val, so the result does not depend on the Windows locale. Lines are
'   longer than the house style allows because each holds one record.
'==============================================================================

'------------------------------------------------------------------------------
' MODULE SETTINGS
'------------------------------------------------------------------------------
    Option Explicit
    Option Private Module


Public Sub RunCaseTests()
'
'==============================================================================
'                                 RunCaseTests
'------------------------------------------------------------------------------
' PURPOSE
'   Run the 19 expected files in file-name order, then restore the workbook.
'==============================================================================
'
        TEST_CaseRunner.BeginSuite 19, 36
        On Error GoTo Failed
        Case01
        Case02
        Case03
        Case04
        Case05
        Case06
        Case07
        Case08
        Case09
        Case10
        Case11
        Case12
        Case13
        Case14
        Case15
        Case16
        Case17
        Case18
        Case19
        TEST_CaseRunner.EndSuite ""
        Exit Sub

Failed:
        TEST_CaseRunner.EndSuite "unexpected error " & Err.Number & ": " & Err.Description

End Sub


Private Sub Case01()
    'tests/expected/cre99-example-1.bcbs.json
        TEST_CaseRunner.BeginCase "cre99-example-1", "BCBS", "2026-09-30", "EUR"
        TEST_CaseRunner.AddNettingSet "EX1", "N", "N", "", "N", "N", "", "0", "0", "0", "0", ""
        TEST_CaseRunner.AddTrade "EX1-T1", "IR", "", "USD", "Linear", "Long", "", "Standard", "", "10000", "30", "", "2036-09-27", "2036-09-27", "", "", "", "", "", ""
        TEST_CaseRunner.AddTrade "EX1-T2", "IR", "", "USD", "Linear", "Short", "", "Standard", "", "10000", "-20", "", "2030-09-29", "2030-09-29", "", "", "", "", "", ""
        TEST_CaseRunner.AddTrade "EX1-T3", "IR", "", "EUR", "Option", "Long", "Put", "Standard", "", "5000", "50", "2027-09-30", "2037-09-27", "2037-09-27", "2027-09-30", "0.06", "0.05", "", "", ""
        TEST_CaseRunner.RunCase
        TEST_CaseRunner.ExpectNumber "T01", "EX1-T1", "adjusted_notional", "78694", "0.5", "0", "published"
        TEST_CaseRunner.ExpectNumber "T02", "EX1-T3", "supervisory_delta", "-0.27", "0.005", "0", "published"
        TEST_CaseRunner.ExpectNumber "T03", "", "add_on.interest_rate", "347", "0.5", "0", "published"
        TEST_CaseRunner.ExpectNumber "T04", "", "exposure_value", "569", "0.5", "0", "published"
End Sub


Private Sub Case02()
    'tests/expected/cre99-example-2.bcbs.json
        TEST_CaseRunner.BeginCase "cre99-example-2", "BCBS", "2026-09-30", "EUR"
        TEST_CaseRunner.AddNettingSet "EX2", "N", "N", "", "N", "N", "", "0", "0", "0", "0", ""
        TEST_CaseRunner.AddTrade "EX2-T1", "CR", "AA", "FIRM A", "Linear", "Long", "", "Standard", "", "10000", "20", "", "2029-09-29", "2029-09-29", "", "", "", "", "", ""
        TEST_CaseRunner.AddTrade "EX2-T2", "CR", "BBB", "FIRM B", "Linear", "Short", "", "Standard", "", "10000", "-40", "", "2032-09-28", "2032-09-28", "", "", "", "", "", ""
        TEST_CaseRunner.AddTrade "EX2-T3", "CR", "IG_INDEX", "CDX.IG", "Linear", "Long", "", "Standard", "", "10000", "0", "", "2031-09-29", "2031-09-29", "", "", "", "", "", ""
        TEST_CaseRunner.RunCase
        TEST_CaseRunner.ExpectNumber "T05", "", "multiplier", "0.965", "0.0005", "0", "published"
        TEST_CaseRunner.ExpectNumber "T06", "", "exposure_value", "381", "0.5", "0", "published"
End Sub


Private Sub Case03()
    'tests/expected/cre99-example-3.bcbs.json
        TEST_CaseRunner.BeginCase "cre99-example-3", "BCBS", "2026-09-30", "EUR"
        TEST_CaseRunner.AddNettingSet "EX3", "N", "N", "", "N", "N", "", "0", "0", "0", "0", ""
        TEST_CaseRunner.AddTrade "EX3-T1", "CO", "OIL_GAS", "CRUDE OIL", "Linear", "Long", "", "Standard", "", "10000", "-50", "", "", "2027-07-01", "", "", "", "", "", ""
        TEST_CaseRunner.AddTrade "EX3-T2", "CO", "OIL_GAS", "CRUDE OIL", "Linear", "Short", "", "Standard", "", "20000", "-30", "", "", "2028-09-29", "", "", "", "", "", ""
        TEST_CaseRunner.AddTrade "EX3-T3", "CO", "METALS", "SILVER", "Linear", "Long", "", "Standard", "", "10000", "100", "", "", "2031-09-29", "", "", "", "", "", ""
        TEST_CaseRunner.RunCase
        TEST_CaseRunner.ExpectNumber "T07", "", "exposure_value", "5406", "2", "0", "published"
End Sub


Private Sub Case04()
    'tests/expected/cre99-example-4.bcbs.json
        TEST_CaseRunner.BeginCase "cre99-example-4", "BCBS", "2026-09-30", "EUR"
        TEST_CaseRunner.AddNettingSet "EX4", "N", "N", "", "N", "N", "", "0", "0", "0", "0", ""
        TEST_CaseRunner.AddTrade "EX4-IRT1", "IR", "", "USD", "Linear", "Long", "", "Standard", "", "10000", "30", "", "2036-09-27", "2036-09-27", "", "", "", "", "", ""
        TEST_CaseRunner.AddTrade "EX4-IRT2", "IR", "", "USD", "Linear", "Short", "", "Standard", "", "10000", "-20", "", "2030-09-29", "2030-09-29", "", "", "", "", "", ""
        TEST_CaseRunner.AddTrade "EX4-IRT3", "IR", "", "EUR", "Option", "Long", "Put", "Standard", "", "5000", "50", "2027-09-30", "2037-09-27", "2037-09-27", "2027-09-30", "0.06", "0.05", "", "", ""
        TEST_CaseRunner.AddTrade "EX4-CRT1", "CR", "AA", "FIRM A", "Linear", "Long", "", "Standard", "", "10000", "20", "", "2029-09-29", "2029-09-29", "", "", "", "", "", ""
        TEST_CaseRunner.AddTrade "EX4-CRT2", "CR", "BBB", "FIRM B", "Linear", "Short", "", "Standard", "", "10000", "-40", "", "2032-09-28", "2032-09-28", "", "", "", "", "", ""
        TEST_CaseRunner.AddTrade "EX4-CRT3", "CR", "IG_INDEX", "CDX.IG", "Linear", "Long", "", "Standard", "", "10000", "0", "", "2031-09-29", "2031-09-29", "", "", "", "", "", ""
        TEST_CaseRunner.RunCase
        TEST_CaseRunner.ExpectNumber "T08", "", "replacement_cost", "40", "0.5", "0", "published"
        TEST_CaseRunner.ExpectNumber "T09", "", "aggregate_add_on", "629", "0.5", "0", "published"
        TEST_CaseRunner.ExpectNumber "T10", "", "exposure_value", "936", "0.6", "0", "published"
End Sub


Private Sub Case05()
    'tests/expected/cre99-example-5.bcbs.json
        TEST_CaseRunner.BeginCase "cre99-example-5", "BCBS", "2026-09-30", "EUR"
        TEST_CaseRunner.AddNettingSet "EX5", "Y", "N", "5", "N", "N", "", "50", "150", "0", "5", ""
        TEST_CaseRunner.AddTrade "EX5-IRT1", "IR", "", "USD", "Linear", "Long", "", "Standard", "", "10000", "30", "", "2036-09-27", "2036-09-27", "", "", "", "", "", ""
        TEST_CaseRunner.AddTrade "EX5-IRT2", "IR", "", "USD", "Linear", "Short", "", "Standard", "", "10000", "-20", "", "2030-09-29", "2030-09-29", "", "", "", "", "", ""
        TEST_CaseRunner.AddTrade "EX5-IRT3", "IR", "", "EUR", "Option", "Long", "Put", "Standard", "", "5000", "50", "2027-09-30", "2037-09-27", "2037-09-27", "2027-09-30", "0.06", "0.05", "", "", ""
        TEST_CaseRunner.AddTrade "EX5-COT1", "CO", "OIL_GAS", "CRUDE OIL", "Linear", "Long", "", "Standard", "", "10000", "-50", "", "", "2027-07-01", "", "", "", "", "", ""
        TEST_CaseRunner.AddTrade "EX5-COT2", "CO", "OIL_GAS", "CRUDE OIL", "Linear", "Short", "", "Standard", "", "20000", "-30", "", "", "2028-09-29", "", "", "", "", "", ""
        TEST_CaseRunner.AddTrade "EX5-COT3", "CO", "METALS", "SILVER", "Linear", "Long", "", "Standard", "", "10000", "100", "", "", "2031-09-29", "", "", "", "", "", ""
        TEST_CaseRunner.RunCase
        TEST_CaseRunner.ExpectNumber "T11", "", "margin_period_of_risk", "14", "0", "0", "published"
        TEST_CaseRunner.ExpectNumber "T12", "", "aggregate_add_on", "1401", "0.5", "0", "published"
        TEST_CaseRunner.ExpectNumber "T13", "", "multiplier", "0.958", "0.0005", "0", "published"
        TEST_CaseRunner.ExpectNumber "T14", "", "exposure_value", "1879", "0.5", "0", "published"
End Sub


Private Sub Case06()
    'tests/expected/cre99-example-5.crr.json
        TEST_CaseRunner.BeginCase "cre99-example-5", "CRR", "2026-09-30", "EUR"
        TEST_CaseRunner.AddNettingSet "EX5", "Y", "N", "5", "N", "N", "", "50", "150", "0", "5", ""
        TEST_CaseRunner.AddTrade "EX5-IRT1", "IR", "", "USD", "Linear", "Long", "", "Standard", "", "10000", "30", "", "2036-09-27", "2036-09-27", "", "", "", "", "", ""
        TEST_CaseRunner.AddTrade "EX5-IRT2", "IR", "", "USD", "Linear", "Short", "", "Standard", "", "10000", "-20", "", "2030-09-29", "2030-09-29", "", "", "", "", "", ""
        TEST_CaseRunner.AddTrade "EX5-IRT3", "IR", "", "EUR", "Option", "Long", "Put", "Standard", "", "5000", "50", "2027-09-30", "2037-09-27", "2037-09-27", "2027-09-30", "0.06", "0.05", "", "", ""
        TEST_CaseRunner.AddTrade "EX5-COT1", "CO", "OIL_GAS", "CRUDE OIL", "Linear", "Long", "", "Standard", "", "10000", "-50", "", "", "2027-07-01", "", "", "", "", "", ""
        TEST_CaseRunner.AddTrade "EX5-COT2", "CO", "OIL_GAS", "CRUDE OIL", "Linear", "Short", "", "Standard", "", "20000", "-30", "", "", "2028-09-29", "", "", "", "", "", ""
        TEST_CaseRunner.AddTrade "EX5-COT3", "CO", "METALS", "SILVER", "Linear", "Long", "", "Standard", "", "10000", "100", "", "", "2031-09-29", "", "", "", "", "", ""
        TEST_CaseRunner.RunCase
        TEST_CaseRunner.ExpectNumber "T15", "", "exposure_value", "1879", "0.5", "0", "illustrative"
End Sub


Private Sub Case07()
    'tests/expected/illustrative-climatic-commodity.crr.json
        TEST_CaseRunner.BeginCase "illustrative-climatic-commodity", "CRR", "2026-09-30", "EUR"
        TEST_CaseRunner.AddNettingSet "CLIMATE", "N", "N", "", "N", "N", "", "0", "0", "0", "0", ""
        TEST_CaseRunner.AddTrade "CL-1", "CO", "CLIMATIC", "HDD LONDON", "Linear", "Long", "", "Standard", "", "1000", "5", "", "", "2027-03-31", "", "", "", "", "", ""
        TEST_CaseRunner.RunCase
        TEST_CaseRunner.ExpectText "T27", "CL-1", "hedging_set", "CO|CLIMATIC|STD", "illustrative"
End Sub


Private Sub Case08()
    'tests/expected/illustrative-credit-quality-step.crr.json
        TEST_CaseRunner.BeginCase "illustrative-credit-quality-step", "CRR", "2026-09-30", "EUR"
        TEST_CaseRunner.AddNettingSet "CQS", "Y", "N", "1", "N", "N", "", "1500000", "2000000", "0", "250000", ""
        TEST_CaseRunner.AddTrade "B03", "CR", "CQS2", "OMEGA AG", "Linear", "Short", "", "Standard", "", "8000000", "120000", "", "2030-09-29", "2030-09-29", "", "", "", "", "", ""
        TEST_CaseRunner.RunCase
        TEST_CaseRunner.ExpectNumber "T28", "B03", "supervisory_factor", "0.0042", "0.000000000001", "0", "illustrative"
End Sub


Private Sub Case09()
    'tests/expected/illustrative-ir-swap-unmargined.bcbs.json
        TEST_CaseRunner.BeginCase "illustrative-ir-swap-unmargined", "BCBS", "2026-01-02", "EUR"
        TEST_CaseRunner.AddNettingSet "NS1", "N", "N", "", "N", "N", "", "0", "0", "0", "0", ""
        TEST_CaseRunner.AddTrade "T1", "IR", "", "EUR", "Linear", "Long", "", "Standard", "", "10000000", "100000", "2026-01-02", "2031-01-02", "2031-01-02", "", "", "", "", "", ""
        TEST_CaseRunner.RunCase
        TEST_CaseRunner.ExpectNumber "replacement_cost", "", "replacement_cost", "100000", "0.000001", "0.000000001", "illustrative"
End Sub


Private Sub Case10()
    'tests/expected/illustrative-ir-swap-unmargined.crr.json
        TEST_CaseRunner.BeginCase "illustrative-ir-swap-unmargined", "CRR", "2026-01-02", "EUR"
        TEST_CaseRunner.AddNettingSet "NS1", "N", "N", "", "N", "N", "", "0", "0", "0", "0", ""
        TEST_CaseRunner.AddTrade "T1", "IR", "", "EUR", "Linear", "Long", "", "Standard", "", "10000000", "100000", "2026-01-02", "2031-01-02", "2031-01-02", "", "", "", "", "", ""
        TEST_CaseRunner.RunCase
        TEST_CaseRunner.ExpectNumber "replacement_cost", "", "replacement_cost", "100000", "0.000001", "0.000000001", "illustrative"
End Sub


Private Sub Case11()
    'tests/expected/illustrative-negative-commodity-price.crr.json
        TEST_CaseRunner.BeginCase "illustrative-negative-commodity-price", "CRR", "2026-09-30", "EUR"
        TEST_CaseRunner.AddNettingSet "NEGCO", "N", "N", "", "N", "N", "", "0", "0", "0", "0", ""
        TEST_CaseRunner.AddTrade "NCO-1", "CO", "OIL_GAS", "WTI", "Option", "Long", "Call", "Standard", "", "10000", "40", "", "", "2027-03-31", "2027-03-31", "-5", "-4", "", "", ""
        TEST_CaseRunner.RunCase
        TEST_CaseRunner.ExpectNumber "T23", "NCO-1", "lambda_shift", "5.5", "0.000000000001", "0", "illustrative"
End Sub


Private Sub Case12()
    'tests/expected/illustrative-negative-ir-forward.bcbs.json
        TEST_CaseRunner.BeginCase "illustrative-negative-ir-forward", "BCBS", "2026-09-30", "EUR"
        TEST_CaseRunner.AddNettingSet "NEGIR", "N", "N", "", "N", "N", "", "0", "0", "0", "0", ""
        TEST_CaseRunner.AddTrade "NIR-C", "IR", "", "EUR", "Option", "Long", "Put", "Standard", "", "10000", "15", "2027-09-30", "2032-09-28", "2032-09-28", "2027-09-30", "-0.002", "0.001", "", "", ""
        TEST_CaseRunner.RunCase
        TEST_CaseRunner.ExpectText "T22", "NIR-C", "trade_status", "EXCLUDED", "illustrative"
        TEST_CaseRunner.ExpectText "netting_set_status", "", "netting_set_status", "INCOMPLETE: 1 of 1 trade(s) rejected", "illustrative"
End Sub


Private Sub Case13()
    'tests/expected/illustrative-negative-ir-forward.crr.json
        TEST_CaseRunner.BeginCase "illustrative-negative-ir-forward", "CRR", "2026-09-30", "EUR"
        TEST_CaseRunner.AddNettingSet "NEGIR", "N", "N", "", "N", "N", "", "0", "0", "0", "0", ""
        TEST_CaseRunner.AddTrade "NIR-C", "IR", "", "EUR", "Option", "Long", "Put", "Standard", "", "10000", "15", "2027-09-30", "2032-09-28", "2032-09-28", "2027-09-30", "-0.002", "0.001", "", "", ""
        TEST_CaseRunner.RunCase
        TEST_CaseRunner.ExpectNumber "T20", "NIR-C", "lambda_shift", "0.003", "0.000000000001", "0", "illustrative"
        TEST_CaseRunner.ExpectNumber "T21", "NIR-C", "supervisory_delta", "-0.9941752720429311", "0.000000001", "0.000000001", "illustrative"
End Sub


Private Sub Case14()
    'tests/expected/illustrative-other-risks.bcbs.json
        TEST_CaseRunner.BeginCase "illustrative-other-risks", "BCBS", "2026-09-30", "EUR"
        TEST_CaseRunner.AddNettingSet "OTHER", "N", "N", "", "N", "N", "", "0", "0", "0", "0", ""
        TEST_CaseRunner.AddTrade "OT-1", "OT", "", "LONGEVITY INDEX X", "Linear", "Long", "", "Standard", "", "10000", "0", "", "", "2028-09-29", "", "", "", "", "", ""
        TEST_CaseRunner.AddTrade "OT-2", "OT", "", "LONGEVITY INDEX X", "Linear", "Short", "", "Standard", "", "4000", "0", "", "", "2029-09-29", "", "", "", "", "", ""
        TEST_CaseRunner.AddTrade "OT-3", "OT", "", "CAT LOSS INDEX Y", "Linear", "Long", "", "Standard", "", "5000", "0", "", "", "2028-03-31", "", "", "", "", "", ""
        TEST_CaseRunner.RunCase
        TEST_CaseRunner.ExpectText "T26", "OT-1", "trade_status", "EXCLUDED", "illustrative"
        TEST_CaseRunner.ExpectText "netting_set_status", "", "netting_set_status", "INCOMPLETE: 3 of 3 trade(s) rejected", "illustrative"
End Sub


Private Sub Case15()
    'tests/expected/illustrative-other-risks.crr.json
        TEST_CaseRunner.BeginCase "illustrative-other-risks", "CRR", "2026-09-30", "EUR"
        TEST_CaseRunner.AddNettingSet "OTHER", "N", "N", "", "N", "N", "", "0", "0", "0", "0", ""
        TEST_CaseRunner.AddTrade "OT-1", "OT", "", "LONGEVITY INDEX X", "Linear", "Long", "", "Standard", "", "10000", "0", "", "", "2028-09-29", "", "", "", "", "", ""
        TEST_CaseRunner.AddTrade "OT-2", "OT", "", "LONGEVITY INDEX X", "Linear", "Short", "", "Standard", "", "4000", "0", "", "", "2029-09-29", "", "", "", "", "", ""
        TEST_CaseRunner.AddTrade "OT-3", "OT", "", "CAT LOSS INDEX Y", "Linear", "Long", "", "Standard", "", "5000", "0", "", "", "2028-03-31", "", "", "", "", "", ""
        TEST_CaseRunner.RunCase
        TEST_CaseRunner.ExpectNumber "T24", "", "add_on.other", "880", "0.000000001", "0", "illustrative"
        TEST_CaseRunner.ExpectNumber "T25", "", "exposure_value", "1232", "0.000000001", "0", "illustrative"
        TEST_CaseRunner.ExpectText "netting_set_status", "", "netting_set_status", "VALID", "illustrative"
End Sub


Private Sub Case16()
    'tests/expected/illustrative-partly-rejected.crr.json
        TEST_CaseRunner.BeginCase "illustrative-partly-rejected", "CRR", "2026-09-30", "EUR"
        TEST_CaseRunner.AddNettingSet "PARTLY", "N", "N", "", "N", "N", "", "0", "0", "0", "0", ""
        TEST_CaseRunner.AddTrade "PR-1", "IR", "", "EUR", "Linear", "Long", "", "Standard", "", "10000000", "100000", "", "2031-09-30", "2031-09-30", "", "", "", "", "", ""
        TEST_CaseRunner.AddTrade "PR-2", "IR", "", "EUR", "Linear", "Long", "", "Standard", "", "10000000", "0", "", "2026-08-31", "2026-08-31", "", "", "", "", "", ""
        TEST_CaseRunner.RunCase
        TEST_CaseRunner.ExpectText "trade_status", "PR-1", "trade_status", "OK", "illustrative"
        TEST_CaseRunner.ExpectText "trade_status", "PR-2", "trade_status", "EXCLUDED", "illustrative"
        TEST_CaseRunner.ExpectText "netting_set_status", "", "netting_set_status", "INCOMPLETE: 1 of 2 trade(s) rejected", "illustrative"
End Sub


Private Sub Case17()
    'tests/expected/illustrative-posted-vm-cap.bcbs.json
        TEST_CaseRunner.BeginCase "illustrative-posted-vm-cap", "BCBS", "2026-09-30", "EUR"
        TEST_CaseRunner.AddNettingSet "VMCAP", "Y", "N", "1", "N", "N", "", "-1300000000", "0", "0", "0", ""
        TEST_CaseRunner.AddTrade "VMC-1", "IR", "", "EUR", "Linear", "Short", "", "Standard", "", "5845000000", "-1100000000", "", "2036-09-27", "2036-09-27", "", "", "", "", "", ""
        TEST_CaseRunner.RunCase
        TEST_CaseRunner.ExpectNumber "T16", "", "exposure_value", "376592788.3471456", "0.000000001", "0.000000001", "illustrative"
End Sub


Private Sub Case18()
    'tests/expected/illustrative-posted-vm-cap.crr.json
        TEST_CaseRunner.BeginCase "illustrative-posted-vm-cap", "CRR", "2026-09-30", "EUR"
        TEST_CaseRunner.AddNettingSet "VMCAP", "Y", "N", "1", "N", "N", "", "-1300000000", "0", "0", "0", ""
        TEST_CaseRunner.AddTrade "VMC-1", "IR", "", "EUR", "Linear", "Short", "", "Standard", "", "5845000000", "-1100000000", "", "2036-09-27", "2036-09-27", "", "", "", "", "", ""
        TEST_CaseRunner.RunCase
        TEST_CaseRunner.ExpectNumber "T17", "", "exposure_value", "40774849.34860364", "0.000000001", "0.000000001", "illustrative"
        TEST_CaseRunner.ExpectText "T18", "", "cap_applied", "Y", "illustrative"
End Sub


Private Sub Case19()
    'tests/expected/illustrative-swaption-forward-1pct.crr.json
        TEST_CaseRunner.BeginCase "illustrative-swaption-forward-1pct", "CRR", "2026-09-30", "EUR"
        TEST_CaseRunner.AddNettingSet "EX1-1PCT", "N", "N", "", "N", "N", "", "0", "0", "0", "0", ""
        TEST_CaseRunner.AddTrade "EU1P-T1", "IR", "", "USD", "Linear", "Long", "", "Standard", "", "10000", "30", "", "2036-09-27", "2036-09-27", "", "", "", "", "", ""
        TEST_CaseRunner.AddTrade "EU1P-T2", "IR", "", "USD", "Linear", "Short", "", "Standard", "", "10000", "-20", "", "2030-09-29", "2030-09-29", "", "", "", "", "", ""
        TEST_CaseRunner.AddTrade "EU1P-T3", "IR", "", "EUR", "Option", "Long", "Put", "Standard", "", "5000", "50", "2027-09-30", "2037-09-27", "2037-09-27", "2027-09-30", "0.01", "0.05", "", "", ""
        TEST_CaseRunner.RunCase
        TEST_CaseRunner.ExpectNumber "T19", "", "exposure_value", "760.4939328393385", "0.000000001", "0.000000001", "illustrative"
End Sub
