#!/usr/bin/env python3
"""Generate tests/modules/TEST_Cases.bas from tests/fixtures and tests/expected.

The generated module holds data only: one procedure per expected file that
writes the fixture into the input sheets through TEST_CaseRunner, runs the engine
and states each expected output. ``--check`` fails when the committed module
differs from what the current JSON files generate.
"""
from __future__ import annotations

import argparse
import json
import sys
from decimal import Decimal
from pathlib import Path
from typing import Any

MODULE = "tests/modules/TEST_Cases.bas"
FIXTURES = "tests/fixtures"
EXPECTED = "tests/expected"

# JSON vocabulary -> the words the Trades sheet expects.
ASSET_CLASS = {"interest_rate": "IR", "foreign_exchange": "FX", "credit": "CR", "equity": "EQ",
               "commodity": "CO", "other": "OT"}
WORDS = {"linear": "Linear", "option": "Option", "cdo": "CDO", "long": "Long", "short": "Short",
         "call": "Call", "put": "Put", "standard": "Standard", "basis": "Basis",
         "volatility": "Volatility"}

HEADER = '''Attribute VB_Name = "TEST_Cases"
'==============================================================================
' MODULE: TEST_Cases
'------------------------------------------------------------------------------
' GENERATED by tools/generate_case_tests.py from tests/fixtures and
' tests/expected. Do not edit: change the JSON files and regenerate.
' python tools/check.py fails when this file is out of date.
'
' PURPOSE
'   Run every numerical test case against the engine. Each procedure writes
'   one fixture into the input sheets for one regime, runs the engine and
'   checks the expected outputs through TEST_CaseRunner.
'
' USAGE
'   Run TEST_Cases.RunCaseTests from the Immediate window in a development
'   workbook. See TEST_CaseRunner for what it changes and restores.
'
' COMPATIBILITY
'   Numbers are passed as text with a "." decimal point and converted with
'   Val, so the result does not depend on the Windows locale. Lines are
'   longer than the house style allows because each holds one record.
'==============================================================================

'------------------------------------------------------------------------------
' MODULE SETTINGS
'------------------------------------------------------------------------------
    Option Explicit
    Option Private Module
'''


def text(value: object) -> str:
    """A VBA string literal; numbers in plain decimal notation, null as empty."""
    if value is None:
        raw = ""
    elif isinstance(value, bool):
        raw = "Y" if value else "N"
    elif isinstance(value, (int, float)):
        raw = format(Decimal(repr(value)), "f")
        if "." in raw:
            raw = raw.rstrip("0").rstrip(".")
    else:
        raw = str(value)
    if not raw.isascii():
        raise ValueError(f"non-ASCII text cannot be written to VBA source: {raw!r}")
    return '"' + raw.replace('"', '""') + '"'


def args(*values: object) -> str:
    return ", ".join(text(v) for v in values)


def case_lines(name: str, fixture: dict[str, Any], expected: dict[str, Any]) -> list[str]:
    ns = fixture["netting_set"]
    lines = [f"Private Sub {name}()", f"    'tests/expected/{fixture['id']}.{expected['regime'].lower()}.json",
             "        TEST_CaseRunner.BeginCase " + args(fixture["id"], expected["regime"],
                                                   fixture["valuation_date"],
                                                   fixture["calculation_currency"]),
             "        TEST_CaseRunner.AddNettingSet " + args(
                 ns["id"], ns["margined"], ns["cleared"], ns["remargin_period_business_days"],
                 ns["large_or_illiquid"], ns["margin_disputes"], ns["mpor_override_business_days"],
                 ns["variation_margin_net_amount"], ns["independent_collateral_net_amount"],
                 ns["threshold_amount"], ns["minimum_transfer_amount"], ns["alpha_factor"])]
    for t in fixture["trades"]:
        lines.append("        TEST_CaseRunner.AddTrade " + args(
            t["id"], ASSET_CLASS[t["asset_class"]], t["sub_class"], t["risk_factor"],
            WORDS[t["instrument"]], WORDS[t["direction"]],
            WORDS[t["option_type"]] if t["option_type"] else None, WORDS[t["nature"]],
            t["hedging_set_label"], t["notional_amount"], t["market_value_amount"],
            t["start_date"], t["end_date"], t["maturity_date"], t["option_expiry_date"],
            t["underlying_price"], t["strike_price"], t["lambda_price"],
            t["attachment_rate"], t["detachment_rate"]))
    lines.append("        TEST_CaseRunner.RunCase")
    for o in expected["outputs"]:
        label = o.get("catalogue") or o["quantity"]
        cls = o["reference"]["class"]
        if "text" in o:
            lines.append("        TEST_CaseRunner.ExpectText " + args(
                label, o.get("trade"), o["quantity"], o["text"], cls))
        elif "value" in o:
            tol = o["tolerance"]
            lines.append("        TEST_CaseRunner.ExpectNumber " + args(
                label, o.get("trade"), o["quantity"], o["value"], tol["absolute"],
                tol["relative"], cls))
        else:
            raise ValueError(f"{fixture['id']}: error outputs are not supported by the engine runner")
    lines += ["End Sub", "", ""]
    return lines


def generate(root: Path) -> str:
    fixtures = {p.stem: json.loads(p.read_text(encoding="utf-8"))
                for p in sorted((root / FIXTURES).glob("*.json"))}
    cases = []
    for path in sorted((root / EXPECTED).glob("*.json")):
        expected = json.loads(path.read_text(encoding="utf-8"))
        cases.append((expected, fixtures[expected["fixture"]]))
    names = [f"Case{i:02d}" for i in range(1, len(cases) + 1)]
    out = HEADER.splitlines()
    out += ["", "", "Public Sub RunCaseTests()", "'",
            "'" + "=" * 78, "'" + "RunCaseTests".center(78).rstrip(), "'" + "-" * 78,
            "' PURPOSE", f"'   Run the {len(cases)} expected files in file-name order, then restore the workbook.",
            "'" + "=" * 78, "'",
            f"        TEST_CaseRunner.BeginSuite {len(cases)}, {sum(len(e['outputs']) for e, _ in cases)}",
            "        On Error GoTo Failed"]
    out += [f"        {name}" for name in names]
    out += ["        TEST_CaseRunner.EndSuite \"\"", "        Exit Sub", "", "Failed:",
            "        TEST_CaseRunner.EndSuite \"unexpected error \" & Err.Number & \": \" & Err.Description",
            "", "End Sub", "", ""]
    for name, (expected, fixture) in zip(names, cases):
        out += case_lines(name, fixture, expected)
    while out and out[-1] == "":
        out.pop()
    return "\r\n".join(out) + "\r\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--check", action="store_true", help="fail if the module is out of date")
    options = parser.parse_args()
    root = options.root.resolve()
    try:
        content = generate(root)
    except (OSError, ValueError, KeyError) as error:
        print(f"ERROR: {error}", file=sys.stderr)
        return 2
    target = root / MODULE
    if options.check:
        current = target.read_bytes().decode("cp1252").replace("\r\n", "\n") if target.exists() else None
        if current != content.replace("\r\n", "\n"):
            print(f"{MODULE} is out of date: run python tools/generate_case_tests.py")
            return 1
        print(f"{MODULE} is up to date")
        return 0
    target.write_bytes(content.encode("cp1252"))
    print(f"wrote {MODULE}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
